const assetData = {
    BTC: {
        name: "Bitcoin",
        symbol: "BTC",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/btc.png",
        iconBackground: "white",
        price: 57500,
        change: "–",
        changeClass: "neutral",
        attributes: ["Zahlungen"],
        info: "Bitcoin ist die erste und bekannteste Kryptowährung. Das Netzwerk basiert auf einer dezentralen Blockchain.",
        supply: "19,7 Mio.",
        available: "93,80 %",
        news: "Bitcoin bleibt als größte Kryptowährung weiter im Fokus der Märkte."
    },

    ETH: {
        name: "Ethereum",
        symbol: "ETH",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/eth.png",
        iconBackground: "black",
        price: 1630,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "NFT", "Web3"],
        info: "Ethereum ist eine Blockchain-Plattform für Smart Contracts, dezentrale Anwendungen und digitale Vermögenswerte.",
        supply: "120,2 Mio.",
        available: "100,00 %",
        news: "Ethereum bleibt wichtiges Netzwerk für dezentrale Anwendungen."
    },

    XRP: {
        name: "XRP",
        symbol: "XRP",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/xrp.png",
        iconBackground: "black",
        price: 1.07,
        change: "–",
        changeClass: "neutral",
        attributes: ["Zahlungen"],
        info: "XRP ist ein digitaler Vermögenswert, der für schnelle und kostengünstige Transaktionen entwickelt wurde.",
        supply: "55,7 Mrd.",
        available: "55,70 %",
        news: "XRP zeigt weiterhin Bewegung im Bereich digitaler Zahlungsnetzwerke."
    },

    SOL: {
        name: "Solana",
        symbol: "SOL",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/sol.png",
        iconBackground: "black",
        price: 75.10,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "NFT", "Web3"],
        info: "Solana ist eine schnelle Blockchain-Plattform für dezentrale Anwendungen, Token und digitale Märkte.",
        supply: "465,2 Mio.",
        available: "100,00 %",
        news: "Solana bleibt bei Anlegern wegen hoher Netzwerkgeschwindigkeit gefragt."
    },

    XLM: {
        name: "Stellar",
        symbol: "XLM",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/xlm.png",
        iconBackground: "white",
        price: 0.193,
        change: "–",
        changeClass: "neutral",
        attributes: ["Zahlungen"],
        info: "Stellar ist ein Blockchain-Netzwerk, das schnelle internationale Zahlungen und digitale Vermögenswerte unterstützt.",
        supply: "29,4 Mrd.",
        available: "58,80 %",
        news: "Stellar bleibt im Bereich digitaler Zahlungsinfrastruktur relevant."
    },

    ADA: {
        name: "Cardano",
        symbol: "ADA",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/ada.png",
        iconBackground: "black",
        price: 0.18,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "Web3"],
        info: "Cardano ist eine Blockchain-Plattform, die auf Sicherheit, Skalierbarkeit und wissenschaftlich fundierte Entwicklung setzt.",
        supply: "35,7 Mrd.",
        available: "79,30 %",
        news: "Cardano bleibt bei langfristig orientierten Krypto-Anlegern im Blick."
    },

    NEAR: {
        name: "NEAR",
        symbol: "NEAR",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/near.png",
        iconBackground: "black",
        price: 1.86,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "Web3"],
        info: "NEAR ist eine skalierbare Blockchain-Plattform für dezentrale Anwendungen und Web3-Projekte.",
        supply: "1,1 Mrd.",
        available: "100,00 %",
        news: "NEAR profitiert von Interesse an skalierbaren Web3-Infrastrukturen."
    },

    TRX: {
        name: "TRON",
        symbol: "TRX",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/trx.png",
        iconBackground: "white",
        price: 0.298,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "Zahlungen"],
        info: "TRON ist ein Blockchain-Netzwerk für digitale Inhalte, Token und dezentrale Anwendungen.",
        supply: "87,4 Mrd.",
        available: "100,00 %",
        news: "TRON bleibt im Bereich günstiger Blockchain-Transaktionen aktiv."
    },

    HBAR: {
        name: "Hedera",
        symbol: "HBAR",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/hbar.png",
        iconBackground: "black",
        price: 0.068,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "Zahlungen", "Web3"],
        info: "Hedera ist ein öffentliches Netzwerk für schnelle Transaktionen, Anwendungen und digitale Vermögenswerte.",
        supply: "35,8 Mrd.",
        available: "71,60 %",
        news: "Hedera bleibt durch Unternehmensanwendungen und Netzwerkausbau im Fokus."
    },

    DOGE: {
        name: "Dogecoin",
        symbol: "DOGE",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/doge.png",
        iconBackground: "white",
        price: 0.072,
        change: "–",
        changeClass: "neutral",
        attributes: ["Zahlungen"],
        info: "Dogecoin ist eine ursprünglich als Meme gestartete Kryptowährung mit großer Community.",
        supply: "145,3 Mrd.",
        available: "100,00 %",
        news: "Dogecoin reagiert weiterhin stark auf Marktstimmung und Community-Aktivität."
    },

    FET: {
        name: "fetch.ai",
        symbol: "FET",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/fet.png",
        iconBackground: "gray",
        price: 0.24,
        change: "–",
        changeClass: "neutral",
        attributes: ["Web3", "Smart Contracts"],
        info: "fetch.ai verbindet Blockchain-Technologie mit Anwendungen aus dem Bereich künstlicher Intelligenz.",
        supply: "2,5 Mrd.",
        available: "100,00 %",
        news: "KI-nahe Krypto-Projekte bleiben bei Anlegern gefragt."
    },

    LINK: {
        name: "Chainlink",
        symbol: "LINK",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/link.png",
        iconBackground: "black",
        price: 7.39,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "Web3"],
        info: "Chainlink stellt dezentrale Oracle-Dienste bereit, die Blockchains mit externen Daten verbinden.",
        supply: "608,1 Mio.",
        available: "60,81 %",
        news: "Chainlink bleibt wichtig für Oracle-Infrastruktur im Blockchain-Bereich."
    },

    AAVE: {
        name: "Aave",
        symbol: "AAVE",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/aave.png",
        iconBackground: "white",
        price: 81.20,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO"],
        info: "Aave ist ein dezentrales Finanzprotokoll für Krypto-Kredite und Liquiditätsmärkte.",
        supply: "14,9 Mio.",
        available: "93,10 %",
        news: "Aave bleibt eines der bekannten Protokolle im DeFi-Sektor."
    },

    AVAX: {
        name: "Avalanche",
        symbol: "AVAX",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/avax.png",
        iconBackground: "white",
        price: 6.40,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "NFT", "Web3"],
        info: "Avalanche ist eine Blockchain-Plattform für dezentrale Anwendungen, Subnetze und digitale Assets.",
        supply: "394,8 Mio.",
        available: "54,80 %",
        news: "Avalanche bleibt durch Skalierungslösungen und Subnetze relevant."
    },

    BCH: {
        name: "Bitcoin Cash",
        symbol: "BCH",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/bch.png",
        iconBackground: "white",
        price: 212.40,
        change: "–",
        changeClass: "neutral",
        attributes: ["Zahlungen"],
        info: "Bitcoin Cash entstand aus Bitcoin und fokussiert sich auf schnelle und günstige Zahlungen.",
        supply: "19,7 Mio.",
        available: "93,80 %",
        news: "Bitcoin Cash bewegt sich weiter im Umfeld klassischer Zahlungs-Coins."
    },

    LTC: {
        name: "Litecoin",
        symbol: "LTC",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/ltc.png",
        iconBackground: "black",
        price: 41.55,
        change: "–",
        changeClass: "neutral",
        attributes: ["Zahlungen"],
        info: "Litecoin wurde von Charlie Lee im Oktober 2011 als eine Abspaltung von Bitcoin hervorgebracht und gilt als eine der frühen alternativen Kryptowährungen.",
        supply: "77,3 Mio.",
        available: "100,00 %",
        news: "Litecoin bleibt als etablierte Kryptowährung am Markt vertreten."
    },

    DOT: {
        name: "Polkadot",
        symbol: "DOT",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/dot.png",
        iconBackground: "black",
        price: 2.45,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "Web3"],
        info: "Polkadot ist ein Netzwerk, das verschiedene Blockchains miteinander verbinden soll.",
        supply: "1,4 Mrd.",
        available: "100,00 %",
        news: "Polkadot bleibt im Bereich interoperabler Blockchain-Netzwerke relevant."
    },

    GRT: {
        name: "The Graph",
        symbol: "GRT",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/grt.png",
        iconBackground: "white",
        price: 0.052,
        change: "–",
        changeClass: "neutral",
        attributes: ["Web3"],
        info: "The Graph ist ein Protokoll zum Indexieren und Abfragen von Blockchain-Daten.",
        supply: "9,5 Mrd.",
        available: "95,00 %",
        news: "The Graph bleibt als Daten-Infrastruktur im Web3-Bereich wichtig."
    },

    ALGO: {
        name: "Algorand",
        symbol: "ALGO",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/algo.png",
        iconBackground: "black",
        price: 0.09,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "Zahlungen", "Web3"],
        info: "Algorand ist eine Blockchain-Plattform für schnelle Transaktionen und dezentrale Anwendungen.",
        supply: "8,1 Mrd.",
        available: "81,00 %",
        news: "Algorand arbeitet weiter an Anwendungen im Blockchain-Ökosystem."
    },

    RNDR: {
        name: "Render",
        symbol: "RNDR",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/rndr.png",
        iconBackground: "black",
        price: 1.70,
        change: "–",
        changeClass: "neutral",
        attributes: ["Web3"],
        info: "Render ist ein Netzwerk für dezentrales GPU-Rendering und digitale Kreativprozesse.",
        supply: "388,6 Mio.",
        available: "75,00 %",
        news: "Render profitiert vom Interesse an GPU- und KI-nahen Projekten."
    },

    MATIC: {
        name: "Polygon",
        symbol: "MATIC",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/matic.png",
        iconBackground: "black",
        price: 0.13,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "NFT", "Gaming", "Web3"],
        info: "Polygon bietet Skalierungslösungen für Ethereum und unterstützt dezentrale Anwendungen.",
        supply: "9,9 Mrd.",
        available: "99,00 %",
        news: "Polygon bleibt als Skalierungslösung für Ethereum im Markt."
    },

    SUI: {
        name: "Sui",
        symbol: "SUI",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/sui.png",
        iconBackground: "black",
        price: 0.70,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "NFT", "Gaming", "Web3"],
        info: "Sui ist eine Blockchain-Plattform, die auf hohe Geschwindigkeit und flexible Anwendungen ausgelegt ist.",
        supply: "2,5 Mrd.",
        available: "25,00 %",
        news: "Sui bleibt durch neue Blockchain-Anwendungen im Blick."
    },

    UNI: {
        name: "Uniswap",
        symbol: "UNI",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/uni.png",
        iconBackground: "black",
        price: 2.96,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO"],
        info: "Uniswap ist ein dezentrales Handelsprotokoll für Token auf Blockchain-Netzwerken.",
        supply: "753,8 Mio.",
        available: "75,38 %",
        news: "Uniswap bleibt eine zentrale Plattform im dezentralen Handel."
    },

    BAND: {
        name: "Band Protocol",
        symbol: "BAND",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/band.png",
        iconBackground: "black",
        price: 0.31,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "DeFi", "Web3"],
        info: "Band Protocol ist ein Oracle-Netzwerk für externe Daten in Smart Contracts.",
        supply: "143,9 Mio.",
        available: "100,00 %",
        news: "Band Protocol bleibt im Oracle-Sektor aktiv."
    },

    SNX: {
        name: "Synthetix",
        symbol: "SNX",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/snx.png",
        iconBackground: "black",
        price: 0.42,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO"],
        info: "Synthetix ist ein DeFi-Protokoll für synthetische Vermögenswerte und Derivate.",
        supply: "327,7 Mio.",
        available: "100,00 %",
        news: "Synthetix bleibt ein bekannter Name im DeFi-Derivatebereich."
    },

    TON: {
        name: "Toncoin",
        symbol: "TON",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/ton.png",
        iconBackground: "gray",
        price: 1.64,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "Zahlungen", "Web3"],
        info: "Toncoin ist der native Coin des TON-Netzwerks, das schnelle Blockchain-Anwendungen unterstützt.",
        supply: "2,4 Mrd.",
        available: "100,00 %",
        news: "Toncoin bleibt durch wachsende Ökosystem-Aktivität im Fokus."
    },

    CHZ: {
        name: "Chiliz",
        symbol: "CHZ",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/chz.png",
        iconBackground: "black",
        price: 0.029,
        change: "–",
        changeClass: "neutral",
        attributes: ["Sport", "Web3"],
        info: "Chiliz ist ein Blockchain-Projekt rund um Sport, Fan-Token und digitale Community-Anwendungen.",
        supply: "8,9 Mrd.",
        available: "100,00 %",
        news: "Chiliz bleibt im Bereich Sport- und Fan-Token aktiv."
    },

    LDO: {
        name: "Lido DAO",
        symbol: "LDO",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/ldo.png",
        iconBackground: "gray",
        price: 0.67,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO"],
        info: "Lido DAO ist ein Protokoll für Liquid Staking auf Ethereum und anderen Netzwerken.",
        supply: "891,7 Mio.",
        available: "89,17 %",
        news: "Lido DAO bleibt ein wichtiger Akteur im Liquid-Staking-Bereich."
    },

    CRV: {
        name: "Curve DAO Token",
        symbol: "CRV",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/crv.png",
        iconBackground: "gray",
        price: 0.20,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO"],
        info: "Curve ist ein DeFi-Protokoll für effizienten Tausch von Stablecoins und ähnlichen Vermögenswerten.",
        supply: "1,2 Mrd.",
        available: "36,00 %",
        news: "Curve bleibt im DeFi-Bereich für Liquiditätspools bekannt."
    },

    AXS: {
        name: "Axie Infinity",
        symbol: "AXS",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/axs.png",
        iconBackground: "black",
        price: 1.60,
        change: "–",
        changeClass: "neutral",
        attributes: ["Gaming", "NFT"],
        info: "Axie Infinity ist ein Blockchain-Spielprojekt mit eigener Token-Ökonomie.",
        supply: "147,8 Mio.",
        available: "54,70 %",
        news: "Axie Infinity bleibt ein bekannter Name im Blockchain-Gaming."
    },

    SKY: {
        name: "Sky",
        symbol: "SKY",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/sky.png",
        iconBackground: "gray",
        price: 0.058,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO"],
        info: "Sky ist ein Krypto-Projekt aus dem DeFi-Umfeld und steht für digitale Finanzanwendungen.",
        supply: "1,0 Mrd.",
        available: "100,00 %",
        news: "Sky bleibt im DeFi-Umfeld im Blick."
    },

    TRUMP: {
        name: "Trump",
        symbol: "TRUMP",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/trump.png",
        iconBackground: "white",
        price: 5.70,
        change: "–",
        changeClass: "neutral",
        attributes: ["Web3"],
        info: "Trump ist ein spekulativer Token, dessen Kurs stark von Marktstimmung und Aufmerksamkeit abhängig sein kann.",
        supply: "200,0 Mio.",
        available: "20,00 %",
        news: "Politisch geprägte Tokens bleiben stark schwankungsanfällig."
    },

    ETC: {
        name: "Ethereum Classic",
        symbol: "ETC",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/etc.png",
        iconBackground: "black",
        price: 13.55,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts"],
        info: "Ethereum Classic ist eine ursprüngliche Abspaltung des Ethereum-Netzwerks.",
        supply: "148,1 Mio.",
        available: "70,30 %",
        news: "Ethereum Classic bleibt ein eigenständiges Proof-of-Work-Netzwerk."
    },

    COMP: {
        name: "Compound",
        symbol: "COMP",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/comp.png",
        iconBackground: "gray",
        price: 27.90,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO"],
        info: "Compound ist ein DeFi-Protokoll für automatisierte Kreditmärkte.",
        supply: "8,4 Mio.",
        available: "84,00 %",
        news: "Compound bleibt im Bereich DeFi-Kredite relevant."
    },

    KNC: {
        name: "Kyber Network Crystal",
        symbol: "KNC",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/knc.png",
        iconBackground: "gray",
        price: 0.29,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi"],
        info: "Kyber Network Crystal ist ein Token aus dem Umfeld dezentraler Liquiditäts- und Handelsprotokolle.",
        supply: "170,1 Mio.",
        available: "100,00 %",
        news: "Kyber bleibt im DeFi-Handelsumfeld aktiv."
    },

    CTSI: {
        name: "Cartesi",
        symbol: "CTSI",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/ctsi.png",
        iconBackground: "gray",
        price: 0.046,
        change: "–",
        changeClass: "neutral",
        attributes: ["Smart Contracts", "Web3"],
        info: "Cartesi verbindet Blockchain-Anwendungen mit Linux-basierten Entwicklungsumgebungen.",
        supply: "821,7 Mio.",
        available: "82,17 %",
        news: "Cartesi arbeitet weiter an skalierbarer Blockchain-Infrastruktur."
    },

    STORJ: {
        name: "Storj",
        symbol: "STORJ",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/storj.png",
        iconBackground: "gray",
        price: 0.16,
        change: "–",
        changeClass: "neutral",
        attributes: ["Web3"],
        info: "Storj ist ein dezentrales Cloud-Speicherprojekt mit Blockchain-Bezug.",
        supply: "390,5 Mio.",
        available: "91,00 %",
        news: "Storj bleibt ein Projekt im Bereich dezentraler Datenspeicherung."
    },

    QNT: {
        name: "Quant",
        symbol: "QNT",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/qnt.png",
        iconBackground: "white",
        price: 76.90,
        change: "–",
        changeClass: "neutral",
        attributes: ["Web3", "Zahlungen"],
        info: "Quant fokussiert sich auf Interoperabilität zwischen verschiedenen Blockchain- und Finanzsystemen.",
        supply: "14,5 Mio.",
        available: "100,00 %",
        news: "Quant bleibt bei Interoperabilitätslösungen im Gespräch."
    },

    "1INCH": {
        name: "1inch",
        symbol: "1INCH",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/1inch.png",
        iconBackground: "black",
        price: 0.16,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi"],
        info: "1inch ist ein DeFi-Aggregator, der verschiedene dezentrale Handelsplätze miteinander vergleicht.",
        supply: "1,2 Mrd.",
        available: "80,00 %",
        news: "1inch bleibt im Bereich dezentraler Handelsaggregation aktiv."
    },

    AUDIO: {
        name: "Audius",
        symbol: "AUDIO",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/audio.png",
        iconBackground: "black",
        price: 0.037,
        change: "–",
        changeClass: "neutral",
        attributes: ["Web3", "NFT"],
        info: "Audius ist ein dezentrales Musikstreaming-Projekt mit eigener Token-Ökonomie.",
        supply: "1,2 Mrd.",
        available: "100,00 %",
        news: "Audius verbindet Musikstreaming mit Blockchain-Technologie."
    },

    YFI: {
        name: "yearn.finance",
        symbol: "YFI",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/yfi.png",
        iconBackground: "gray",
        price: 3950,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO"],
        info: "yearn.finance ist ein DeFi-Protokoll für automatisierte Renditestrategien.",
        supply: "33.500",
        available: "100,00 %",
        news: "yearn.finance bleibt ein bekannter Name im DeFi-Sektor."
    },

    LRC: {
        name: "Loopring",
        symbol: "LRC",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/lrc.png",
        iconBackground: "black",
        price: 0.061,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "Web3"],
        info: "Loopring ist ein Protokoll für skalierbaren dezentralen Handel und Layer-2-Technologie.",
        supply: "1,3 Mrd.",
        available: "97,00 %",
        news: "Loopring bleibt im Layer-2-Handelsumfeld vertreten."
    },

    BNT: {
        name: "Bancor",
        symbol: "BNT",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/bnt.png",
        iconBackground: "gray",
        price: 0.34,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi"],
        info: "Bancor ist ein DeFi-Protokoll für automatisierte Liquidität und Token-Tausch.",
        supply: "125,4 Mio.",
        available: "100,00 %",
        news: "Bancor bleibt ein früher Akteur im DeFi-Sektor."
    },

    BAT: {
        name: "Basic Attention Token",
        symbol: "BAT",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/bat.png",
        iconBackground: "black",
        price: 0.13,
        change: "–",
        changeClass: "neutral",
        attributes: ["Web3", "Zahlungen"],
        info: "Basic Attention Token wird im Umfeld digitaler Werbung und des Brave-Browsers verwendet.",
        supply: "1,5 Mrd.",
        available: "100,00 %",
        news: "BAT bleibt mit digitaler Werbung und Browser-Ökosystem verbunden."
    },

    MELANIA: {
        name: "Melania",
        symbol: "MELANIA",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/melania.png",
        iconBackground: "white",
        price: 0.12,
        change: "–",
        changeClass: "neutral",
        attributes: ["Web3"],
        info: "Melania ist ein spekulativer Token mit hoher Abhängigkeit von Marktstimmung und Aufmerksamkeit.",
        supply: "1,0 Mrd.",
        available: "15,00 %",
        news: "Meme- und Aufmerksamkeitstokens bleiben besonders volatil."
    },

    IMX: {
        name: "Immutable X",
        symbol: "IMX",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/imx.png",
        iconBackground: "black",
        price: 0.31,
        change: "–",
        changeClass: "neutral",
        attributes: ["Gaming", "NFT", "Web3"],
        info: "Immutable X ist ein Projekt für NFTs, Gaming und skalierbare Blockchain-Anwendungen.",
        supply: "1,5 Mrd.",
        available: "75,00 %",
        news: "Immutable X bleibt im Blockchain-Gaming- und NFT-Bereich aktiv."
    },

    OGN: {
        name: "Origin Protocol",
        symbol: "OGN",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/ogn.png",
        iconBackground: "gray",
        price: 0.043,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "NFT", "Web3"],
        info: "Origin Protocol entwickelt Blockchain-Produkte für digitale Märkte und dezentrale Anwendungen.",
        supply: "650,0 Mio.",
        available: "65,00 %",
        news: "Origin Protocol bleibt im Bereich dezentraler Anwendungen vertreten."
    },

    SUSHI: {
        name: "SushiSwap",
        symbol: "SUSHI",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/sushi.png",
        iconBackground: "black",
        price: 0.32,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO"],
        info: "SushiSwap ist ein dezentrales Handelsprotokoll mit eigener Token-Ökonomie.",
        supply: "231,9 Mio.",
        available: "92,00 %",
        news: "SushiSwap bleibt Teil des dezentralen Handelsökosystems."
    },

    ZRX: {
        name: "0x",
        symbol: "ZRX",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/zrx.png",
        iconBackground: "white",
        price: 0.18,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi"],
        info: "0x ist ein Protokoll für dezentralen Token-Handel und Liquiditätsinfrastruktur.",
        supply: "847,5 Mio.",
        available: "84,75 %",
        news: "0x bleibt im Bereich dezentraler Handelsinfrastruktur aktiv."
    },

    SAND: {
        name: "The Sandbox",
        symbol: "SAND",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/sand.png",
        iconBackground: "gray",
        price: 0.16,
        change: "–",
        changeClass: "neutral",
        attributes: ["Gaming", "NFT", "Web3"],
        info: "The Sandbox ist ein Metaverse- und Gaming-Projekt mit eigener Token-Ökonomie.",
        supply: "2,3 Mrd.",
        available: "76,00 %",
        news: "The Sandbox bleibt im Bereich Blockchain-Gaming und Metaverse vertreten."
    },

    UMA: {
        name: "UMA",
        symbol: "UMA",
        type: "CRYPTO",
        typeLabel: "Crypto",
        icon: "assets/icons/uma.png",
        iconBackground: "black",
        price: 0.74,
        change: "–",
        changeClass: "neutral",
        attributes: ["DeFi", "DAO", "Smart Contracts"],
        info: "UMA ist ein Protokoll für dezentrale Finanzverträge und Oracles.",
        supply: "81,2 Mio.",
        available: "81,20 %",
        news: "UMA bleibt im DeFi- und Oracle-Umfeld aktiv."
    }
};